ShopTARgv23/Models/Spaceships/FileToApiViewModel.cs
namespace ShopTARgv23.Models.Spaceships
{
    public class FileToApiViewModel
    {
        public Guid? ImageId { get; set; }

        public string? FilePath { get; set; }

        public Guid? SpaceshipsId { get; set; }
    }
}

ShopTARgv23/Models/Spaceships/FileToApiViewModels.cs
namespace ShopTARgv23.Models.Spaceships
{
    public class FileToApiViewModels
    {
        public Guid? ImageId { get; set; }

        public string? FilePath { get; set; }

        public Guid? SpaceshipsId { get; set; }
    }
}

ShopTARgv23/Models/Spaceships/SpaceshipCreateUpdateViewModel.cs
namespace ShopTARgv23.Models.Spaceships
{
    public class SpaceshipCreateUpdateViewModel
    {
        public Guid? Id { get; set; }

        public string? Name { get; set; }

        public string? Type { get; set; }

        public DateTime? BuiltDate { get; set; }

        public int? CargoWeight { get; set; }

        public int? Crew { get; set; }

        public int? EnginePower { get; set; }

        public List<IFormFile> Files { get; set; }

        public List<FileToApiViewModel> FileToApiViewModels { get; set; }
            = new List<FileToApiViewModel>();

        public DateTime? CreatedAt { get; set; }

        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARgv23/Models/Spaceships/SpaceshipDeleteViewModel.cs
namespace ShopTARgv23.Models.Spaceships
{
    public class SpaceshipDeleteViewModel
    {
        public Guid? Id { get; set; }

        public string? Name { get; set; }

        public string? Type { get; set; }

        public DateTime? BuiltDate { get; set; }

        public int? CargoWeight { get; set; }

        public int? Crew { get; set; }

        public int? EnginePower { get; set; }

        public List<FileToApiViewModel> FileToApiViewModels { get; set; }
            = new List<FileToApiViewModel>();

        public DateTime? CreatedAt { get; set; }

        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARgv23/Models/Spaceships/SpaceshipDetailsViewModel.cs
namespace ShopTARgv23.Models.Spaceships
{
    public class SpaceshipDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string? Name { get; set; }
        public string? Type { get; set; }
        public DateTime? BuiltDate { get; set; }
        public int? CargoWeight { get; set; }
        public int? Crew { get; set; }
        public int? EnginePower { get; set; }
        public List<FileToApiViewModel> FileToApiViewModels { get; set; }
            = new List<FileToApiViewModel>();
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARgv23/Models/Spaceships/SpaceshipsIndexViewModel.cs
namespace ShopTARgv23.Models.Spaceships
{
    public class SpaceshipsIndexViewModel
    {
        public Guid? Id { get; set; }
        public string? Name { get; set; }
        public string? Type { get; set; }
        public DateTime? BuiltDate { get; set; }
        public int? CargoWeight { get; set; }
        public int? Crew { get; set; }
        public int? EnginePower { get; set; }
    }
}

ShopTARgv23/Controllers/SpaceshipsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopTARgv23.Core.Domain;
using ShopTARgv23.Core.Dto;
using ShopTARgv23.Core.ServiceInterface;
using ShopTARgv23.Data;
using ShopTARgv23.Models.Spaceships;

namespace ShopTARgv23.Controllers
{
    public class SpaceshipsController : Controller
    {
        private readonly ShopTARgv23Context _context;
        private readonly ISpaceshipServices _spaceshipServices;
        private readonly IFileServices _fileServices;

        public SpaceshipsController
            (
                ShopTARgv23Context context,
                ISpaceshipServices spaceshipServices,
                IFileServices fileServices

            )
        {
            _context = context;
            _spaceshipServices = spaceshipServices;
            _fileServices = fileServices;

        }

        public IActionResult Index()
        {
            var result =  _context.Spaceships
                .Select(x => new SpaceshipsIndexViewModel
                {
                   Id = x.Id,
                   Name = x.Name,
                   Type = x.Type,
                   BuiltDate = x.BuiltDate,
                   EnginePower = x.EnginePower
                });
            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            SpaceshipCreateUpdateViewModel spaceship = new();

            return View("CreateUpdate", spaceship);
        }


        [HttpPost]
        public async Task<IActionResult> Create(SpaceshipCreateUpdateViewModel vm)
        {
            var dto = new SpaceshipDto()
            {
                Id = vm.Id,
                Name = vm.Name,
                Type = vm.Type,
                BuiltDate = vm.BuiltDate,
                CargoWeight = vm.CargoWeight,
                Crew = vm.Crew,
                EnginePower = vm.EnginePower,
                Files = vm.Files,
                Image = vm.FileToApiViewModels
                    .Select( x => new FileToApiDto
                    {
                        Id = x.ImageId,
                        ExistingFilePath = x.FilePath,
                        SpaceshipsId = x.SpaceshipsId,
                    }).ToArray()
                    
            };

            var result = await _spaceshipServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var spaceship = await _spaceshipServices.DetailsAsync(id);

            if (spaceship == null)
            {
                return NotFound();
            }

            var images = await _context.FileToApis
                .Where(x => x.SpaceshipId == id)
                .Select(y => new FileToApiViewModel
                {
                    FilePath = y.ExistingFilePath,
                    ImageId = y.Id
                }).ToArrayAsync();

            var vm = new SpaceshipDetailsViewModel();

            vm.Id = spaceship.Id;
            vm.Name = spaceship.Name;
            vm.Type = spaceship.Type;
            vm.BuiltDate = spaceship.BuiltDate;
            vm.CargoWeight = spaceship.CargoWeight;
            vm.Crew = spaceship.Crew;
            vm.EnginePower = spaceship.EnginePower;
            vm.CreatedAt = spaceship.CreatedAt;
            vm.ModifiedAt = spaceship.ModifiedAt;
            vm.FileToApiViewModels.AddRange(images);

            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var spaceship = await _spaceshipServices.DetailsAsync(id);

            if (spaceship == null)
            {
                return NotFound();
            }

            var images = await _context.FileToApis
                .Where(x => x.SpaceshipId == id)
                .Select(y => new FileToApiViewModel
                {
                    FilePath = y.ExistingFilePath,
                    ImageId = y.Id
                }).ToArrayAsync();

            var vm = new SpaceshipCreateUpdateViewModel();

            vm.Id = spaceship.Id;
            vm.Name = spaceship.Name;
            vm.Type = spaceship.Type;
            vm.BuiltDate = spaceship.BuiltDate;
            vm.CargoWeight = spaceship.CargoWeight;
            vm.Crew = spaceship.Crew;
            vm.EnginePower = spaceship.EnginePower;
            vm.FileToApiViewModels.AddRange(images);

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(SpaceshipCreateUpdateViewModel vm)
        {
            var dto = new SpaceshipDto()
            {

                Id = vm.Id,
                Name = vm.Name,
                Type = vm.Type,
                BuiltDate = vm.BuiltDate,
                CargoWeight = vm.CargoWeight,
                Crew = vm.Crew,
                EnginePower = vm.EnginePower,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files,
                Image = vm.FileToApiViewModels
                    .Select(x => new FileToApiDto
                    {
                        Id = x.ImageId,
                        ExistingFilePath = x.FilePath,
                        SpaceshipsId = x.SpaceshipsId
                    }).ToArray()
            };


            var result = await _spaceshipServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var spaceship = await _spaceshipServices.DetailsAsync(id);

            if (spaceship == null)
            {
                return NotFound();
            }
            var images = await _context.FileToApis
                .Where(x => x.SpaceshipId == id)
                .Select(y => new FileToApiViewModel
                {
                    FilePath = y.ExistingFilePath,
                    ImageId = y.Id
                }).ToArrayAsync();

            var vm = new SpaceshipDeleteViewModel();

            vm.Id = spaceship.Id;
            vm.Name = spaceship.Name;
            vm.Type = spaceship.Type;
            vm.BuiltDate = spaceship.BuiltDate;
            vm.CargoWeight = spaceship.CargoWeight;
            vm.Crew = spaceship.Crew;
            vm.EnginePower = spaceship.EnginePower;
            vm.CreatedAt = spaceship.CreatedAt;
            vm.ModifiedAt = spaceship.ModifiedAt;

            vm.FileToApiViewModels.AddRange(images);
            // Peate tegema Delete view modeli ja siin ära mappima spaceship muutujuga

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var spaceship = await _spaceshipServices.Delete(id);

            if (spaceship == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveImage(FileToApiViewModel vm)
        {
            var dto = new FileToApiDto()
            {
                Id = vm.ImageId
            };

            var image = await _fileServices.RemoveImageFromApi(dto);

            if (image == null){ return RedirectToAction(nameof(Index)); }

            return RedirectToAction(nameof(Index));
        }
    }
}

ShopTARgv23/Views/Spaceships/CreateUpdate.cshtml
@model ShopTARgv23.Models.Spaceships.SpaceshipCreateUpdateViewModel

@if (Model.Id.HasValue)
{   
    ViewData["Title"] = "Spaceship Update";
}
else
{
    ViewData["Title"] = "Spaceship Create";
}

<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="ModifiedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Type" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Type" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="BuiltDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="BuiltDate" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="CargoWeight" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="CargoWeight" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Crew" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Crew" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="EnginePower" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="EnginePower" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Files" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-5">
                <div class="custom-file">
                    <input class="form-control custom-file-label" asp-for="Files" multiple type="file" />
                    <label class="custom-file-label">Choose File...</label>
                </div>
            </div>
        </div>

        @foreach (var images in Model.FileToApiViewModels)
        {
            <partial name="_Images" model="images" />
            <input asp-action="removeImage" asp-controller="spaceships" asp-route-imageId="@images.ImageId" type="submit" class="btn btn-danger" value="Remove Image" />
        }

        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="spaceships" type="submit" class="btn btn-primary" value="Update" />
        }
        else
        {
            <input asp-action="create" asp-controller="spaceships" type="submit" class="btn btn-primary" value="Create" />
        }
        <input asp-action="index" asp-controller="spaceships" type="submit" class="btn btn-outline-secondary" value="Back" />
    </form>
</div>


@section Scripts
{
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileLabel = $(this).next('.custom-file-label');
                var files = $(this)[0].files;
                if (files.length > 1) {
                    fileLabel.html(files.length + ' files selected');
                }
                else if (files.length == 1) {
                    fileLabel.html(files[0].name);
                }
            });
        });
    </script>
}

ShopTARgv23/Views/Spaceships/Delete.cshtml
@model ShopTARgv23.Models.Spaceships.SpaceshipDeleteViewModel

@{
    ViewData["Title"] = "Spaceship Delete";
}

<div>
    <h4>Spaceships</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Name)
        </div>

        <div class="form-group row">
            <label asp-for="Type" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Type)
        </div>

        <div class="form-group row">
            <label asp-for="BuiltDate" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuiltDate)
        </div>

        <div class="form-group row">
            <label asp-for="CargoWeight" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CargoWeight)
        </div>

        <div class="form-group row">
            <label asp-for="Crew" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Crew)
        </div>

        <div class="form-group row">
            <label asp-for="EnginePower" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.EnginePower)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>
        
        @foreach (var images in Model.FileToApiViewModels)
        {
            <partial name="_Images" model="images" />
        }

        <form asp-action="DeleteConfirmation">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a asp-action="Index" asp-controller="spaceships" class="btn btn-success">Back</a>
        </form>
    </dl>
</div>

ShopTARgv23/Views/Spaceships/Details.cshtml
@model ShopTARgv23.Models.Spaceships.SpaceshipDetailsViewModel

@{
    ViewData["Title"] = "Spaceship Detail";
}

<div>
    <h4>Spaceship</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Name)
        </div>

        <div class="form-group row">
            <label asp-for="Type" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Type)
        </div>

        <div class="form-group row">
            <label asp-for="BuiltDate" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuiltDate)
        </div>

        <div class="form-group row">
            <label asp-for="CargoWeight" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CargoWeight)
        </div>

        <div class="form-group row">
            <label asp-for="Crew" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Crew)
        </div>

        <div class="form-group row">
            <label asp-for="EnginePower" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.EnginePower)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>

        @foreach(var images in Model.FileToApiViewModels)
        {
            <partial name="_Images" model="images" />
        }

    </dl>
    <a asp-action="Index" asp-controller="spaceships" class="btn btn-danger">Back</a>
</div>

ShopTARgv23/Views/Spaceships/_Images.cshtml
@model ShopTARgv23.Models.Spaceships.FileToApiViewModel

@{
    var photoPath = "~/MultipleFileUpload/" + (@Model.FilePath ?? "noimage.jpg");
    // Kui pilti ei ole ankeedis e multippleFileUploadis, siis n'ita noimage.jpg
}

<div class="form-group row col-sm-4 offset-2">
    <div>@Model.FilePath</div>
    <img class="card-img-top" src="@photoPath" asp-append-version="true" />
</div>

ShopTARgv23/Views/Spaceships/index.cshtml
@model IEnumerable<ShopTARgv23.Models.Spaceships.SpaceshipsIndexViewModel>

@{
    int rowNumber = 1;
    ViewData["Title"] = "Spaceship";
}

<div>
    <a asp-action="create" asp-controller="Spaceships" type="submit" class="btn btn-primary">Create</a>
</div>

<br />

<form method="post">
    <table class="table table-hover">
        <thed>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Name</th>
                <th scope="col">Type</th>
                <th scope="col">Build date</th>
                <th scope="col">Engine Power</th>
                <th scope="col"></th>
            </tr>
        </thed>
        <tbody>
            @foreach( var spaceships in Model)
            {
                <tr>
                    <td>@rowNumber</td>
                    <td>@spaceships.Name</td>
                    <td>@spaceships.Type</td>
                    <td>@spaceships.BuiltDate</td>
                    <td>@spaceships.EnginePower</td>
                    <td>
                        <a asp-action="details" asp-controller="spaceships" asp-route-id="@spaceships.Id" class="btn btn-info">Details</a>
                        <a asp-action="update" asp-controller="spaceships" asp-route-id="@spaceships.Id" class="btn btn-primary">Update</a>
                        <a asp-action="delete" asp-controller="spaceships" asp-route-id="@spaceships.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>

                rowNumber++;
            }
        </tbody>
    </table>
</form>