ShopTARgv23/Models/Kindergartens/KindergartensCreateUpdateViewModel.cs
namespace ShopTARgv23.Models.Kindergartens
{
    public class KindergartensCreateUpdateViewModel
    {
        public Guid? Id { get; set; }

        public string? GroupName { get; set; }

        public int? ChildrenCount { get; set; }

        public string? KindergartenName { get; set; }

        public string? Teacher { get; set; }

        public DateTime? CreatedAt { get; set; }

        public DateTime? UpdatedAt { get; set; }

        public List<IFormFile> Files { get; set; }
        public List<KindergartensImageViewModel> Image { get; set; }
            = new List<KindergartensImageViewModel>();
    }
}

ShopTARgv23/Models/Kindergartens/KindergartensDeleteViewModel.cs
namespace ShopTARgv23.Models.Kindergartens
{
    public class KindergartensDeleteViewModel
    {
        public Guid? Id { get; set; }

        public string? GroupName { get; set; }

        public int? ChildrenCount { get; set; }

        public string? KindergartenName { get; set; }

        public string? Teacher { get; set; }

        public DateTime? CreatedAt { get; set; }

        public DateTime? UpdatedAt { get; set; }

        public List<KindergartensImageViewModel> Image { get; set; }
            = new List<KindergartensImageViewModel>();
    }
}

ShopTARgv23/Models/Kindergartens/KindergartensDetailViewModel.cs
namespace ShopTARgv23.Models.Kindergartens
{
    public class KindergartensDetailViewModel
    {
        public Guid? Id { get; set; }

        public string? GroupName { get; set; }

        public int? ChildrenCount { get; set; }

        public string? KindergartenName { get; set; }

        public string? Teacher { get; set; }

        public DateTime? CreatedAt { get; set; }

        public DateTime? UpdatedAt { get; set; }

        public List<KindergartensImageViewModel> Image { get; set; }
            = new List<KindergartensImageViewModel>();

    }
}

ShopTARgv23/Models/Kindergartens/KindergartensIndexViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ShopTARgv23.Models.Kindergartens
{
    public class KindergartensIndexViewModel
    {
        public Guid? Id { get; set; }

        public string? GroupName { get; set; }

        public int? ChildrenCount { get; set; }

        public string? KindergartenName { get; set; }

        public string? Teacher { get; set; }

        public DateTime? CreatedAt { get; set; }

        public DateTime? UpdatedAt { get; set; }
    }
}

ShopTARgv23/Controllers/KindergartensController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopTARgv23.ApplicationService.Services;
using ShopTARgv23.Core.Domain;
using ShopTARgv23.Core.Dto;
using ShopTARgv23.Core.ServiceInterface;
using ShopTARgv23.Data;
using ShopTARgv23.Models.Kindergartens;
using ShopTARgv23.Models.Spaceships;
using static System.Net.Mime.MediaTypeNames;

namespace ShopTARgv23.Controllers
{
    public class KindergartensController : Controller
    {

        private readonly ShopTARgv23Context _context;
        private readonly IKindergartenServices _KindergartenServices;
        private readonly IFileServices _fileServices;

        public KindergartensController
            (
                ShopTARgv23Context context,
                IKindergartenServices KindergartenServices,
                IFileServices fileServices
            )
        {
            _context = context;
            _KindergartenServices = KindergartenServices;
            _fileServices = fileServices;
        }

        public IActionResult Index()
        {
            var result = _context.Kindergartens
                .Select(x => new KindergartensIndexViewModel
                {
                    Id = x.Id,
                    GroupName = x.GroupName,
                    ChildrenCount = x.ChildrenCount,
                    KindergartenName = x.KindergartenName,
                    Teacher = x.Teacher,
                    CreatedAt = x.CreatedAt
                });
            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            KindergartensCreateUpdateViewModel kindergarten = new();

            return View("CreateUpdate", kindergarten);
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(KindergartensCreateUpdateViewModel vm)
        {
            var dto = new KindergartenDto()
            {
                Id = vm.Id,
                GroupName = vm.GroupName,
                ChildrenCount = vm.ChildrenCount,
                KindergartenName = vm.KindergartenName,
                Teacher = vm.Teacher,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
                Files = vm.Files,
                Image = vm.Image
                    .Select(x => new FileToDatabaseDto
                    {
                        Id = x.ImageId,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        IdFromModel = x.KindergartensId
                    }).ToArray()
            };

            var result = await _KindergartenServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var kindergarten = await _KindergartenServices.DetailsAsync(id);

            if (kindergarten == null)
            {
                return NotFound();
            }

            var images = await _context.FileToDatabases
                .Where(x => x.IdFromModel == id)
                .Select(y => new KindergartensImageViewModel
                {
                    KindergartensId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new KindergartensDetailViewModel();

            vm.Id = kindergarten.Id;
            vm.GroupName = kindergarten.GroupName;
            vm.ChildrenCount = kindergarten.ChildrenCount;
            vm.KindergartenName = kindergarten.KindergartenName;
            vm.Teacher = kindergarten.Teacher;
            vm.CreatedAt = kindergarten.CreatedAt;
            vm.UpdatedAt = kindergarten.UpdatedAt;
            vm.Image.AddRange(images);

            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var kindergarten = await _KindergartenServices.DetailsAsync(id);

            if (kindergarten == null)
            {
                return NotFound();
            }

            var images = await _context.FileToDatabases
                .Where(x => x.IdFromModel == id)
                .Select(y => new KindergartensImageViewModel
                {
                    KindergartensId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new KindergartensCreateUpdateViewModel();

            vm.Id = kindergarten.Id;
            vm.GroupName = kindergarten.GroupName;
            vm.ChildrenCount = kindergarten.ChildrenCount;
            vm.KindergartenName = kindergarten.KindergartenName;
            vm.Teacher = kindergarten.Teacher;
            vm.CreatedAt = kindergarten.CreatedAt;
            vm.UpdatedAt = kindergarten.UpdatedAt;
            vm.Image.AddRange(images);

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(KindergartensCreateUpdateViewModel vm)
        {
            var dto = new KindergartenDto()
            {
                Id = vm.Id,
                GroupName = vm.GroupName,
                ChildrenCount = vm.ChildrenCount,
                KindergartenName = vm.KindergartenName,
                Teacher = vm.Teacher,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
                Files = vm.Files,
                Image = vm.Image
                    .Select(x => new FileToDatabaseDto
                    {
                        Id = x.ImageId,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        IdFromModel = x.KindergartensId
                    }).ToArray(),
            };

            var result = await _KindergartenServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var kindergarten = await _KindergartenServices.DetailsAsync(id);

            if (kindergarten == null)
            {
                return NotFound();
            }

            var image = await _context.FileToDatabases
                .Where(x => x.IdFromModel == id)
                .Select(y => new KindergartensImageViewModel
                {
                    KindergartensId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new KindergartensDeleteViewModel();

            vm.Id = kindergarten.Id;
            vm.GroupName = kindergarten.GroupName;
            vm.ChildrenCount = kindergarten.ChildrenCount;
            vm.KindergartenName = kindergarten.KindergartenName;
            vm.Teacher = kindergarten.Teacher;
            vm.CreatedAt = kindergarten.CreatedAt;
            vm.UpdatedAt = kindergarten.UpdatedAt;
            vm.Image.AddRange(image);

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var kindergarten = await _KindergartenServices.Delete(id);

            if (kindergarten == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveImage(KindergartensImageViewModel file)
        {
            var dto = new FileToDatabaseDto()
            {
                Id = file.ImageId
            };

            var image = await _fileServices.RemoveImageFromDatabase(dto);

            if (image == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ShopTARgv23/Views/Kindergartens/CreateUpdate.cshtml
@model ShopTARgv23.Models.Kindergartens.KindergartensCreateUpdateViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}

<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="UpdatedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="GroupName" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="ChildrenCount" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="KindergartenName" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Teacher" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Teacher" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Files" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-5">
                <div class="custom-file">
                    <input class="form-control custom-file-label" asp-for="Files" multiple type="file" />
                    <label class="custom-file-label">Choose File...</label>
                </div>
            </div>
        </div>

        @foreach (var images in Model.Image)
        {
            <partial name="_Images" model="images" />
            <input asp-action="removeImage" asp-controller="Kindergartens" asp-route-imageId="@images.ImageId" type="submit" class="btn btn-danger" value="Remove Image" />
        }

        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="Kindergartens" type="submit" class="btn btn-primary" value="Update" />
        }
        else
        {
            <input asp-action="create" asp-controller="Kindergartens" type="submit" class="btn btn-primary" value="Create" />
        }
        <input asp-action="index" asp-controller="Kindergartens" type="submit" class="btn btn-outline-secondary" value="Back" />
    </form>
</div>

ShopTARgv23/Views/Kindergartens/Delete.cshtml
@model ShopTARgv23.Models.Kindergartens.KindergartensDeleteViewModel

<h1>Update</h1>

<div>
    <h4>Kindergarten</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.GroupName)
        </div>

        <div class="form-group row">
            <label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ChildrenCount)
        </div>

        <div class="form-group row">
            <label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.KindergartenName)
        </div>

        <div class="form-group row">
            <label asp-for="Teacher" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Teacher)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.UpdatedAt)
        </div>

        @foreach (var file in Model.Image)
        {
            <partial name="_Images" model="file" />
        }

        <form asp-action="DeleteConfirmation">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a asp-action="Index" asp-controller="Kindergartens" class="btn btn-success">Back</a>
        </form>
    </dl>
</div>

ShopTARgv23/Views/Kindergartens/Details.cshtml
@model ShopTARgv23.Models.Kindergartens.KindergartensDetailViewModel

<h1>Details</h1>

<div>
    <h4>Kindergarten</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.GroupName)
        </div>

        <div class="form-group row">
            <label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ChildrenCount)
        </div>

        <div class="form-group row">
            <label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.KindergartenName)
        </div>

        <div class="form-group row">
            <label asp-for="Teacher" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Teacher)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.UpdatedAt)
        </div>

        @foreach (var images in Model.Image)
        {
            <partial name="_Images" model="images" />
        }
    </dl>
    <a asp-action="Index" asp-controller="Kindergartens" class="btn btn-danger">Back</a>
</div>

ShopTARgv23/Views/Kindergartens/Index.cshtml
@model IEnumerable<ShopTARgv23.Models.Kindergartens.KindergartensIndexViewModel>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="create" asp-controller="Kindergartens" type="submit" class="btn btn-primary">Create</a>
</div>

<div class="h1">
    Kindergarten
</div>

<form method="post">
    <table class="table table-hover">
        <thed>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">GroupName</th>
                <th scope="col">ChildrenCount</th>
                <th scope="col">KindergartenName</th>
                <th scope="col">Teacher</th>
                <th scope="col"></th>
            </tr>
        </thed>
        <tbody>
            @foreach (var Kindergarten in Model)
            {
                <tr>
                    <td>@rowNumber</td>
                    <td>@Kindergarten.GroupName</td>
                    <td>@Kindergarten.ChildrenCount</td>
                    <td>@Kindergarten.KindergartenName</td>
                    <td>@Kindergarten.Teacher</td>
                    <td>
                        <a asp-action="details" asp-controller="Kindergartens" asp-route-id="@Kindergarten.Id" class="btn btn-info">Details</a>
                        <a asp-action="update" asp-controller="Kindergartens" asp-route-id="@Kindergarten.Id" class="btn btn-primary">Update</a>
                        <a asp-action="delete" asp-controller="Kindergartens" asp-route-id="@Kindergarten.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>

                rowNumber++;
            }
        </tbody>
    </table>
</form>